/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author tolga
 */
public class SinavÖrnek5 extends javax.swing.JFrame {
        List<String> il=new ArrayList<>();
        List<String> ist=new ArrayList<>();
        List<String> ada=new ArrayList<>();
        List<String> isp=new ArrayList<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SinavÖrnek5.class.getName());

    /**
     * Creates new form SinavÖrnek5
     */
    public SinavÖrnek5() {
        

        initComponents();
        jComboBox1.removeAllItems();
        jComboBox2.removeAllItems();
        
        try{BufferedReader oku = new BufferedReader(new FileReader("C:\\Users\\tolga\\OneDrive\\Masaüstü\\VizeSinaviOncesiUygulama\\iller.txt"));
                String satir = oku.readLine();
                while (satir != null) {
                    il.add(satir);
                    satir = oku.readLine();
                }
        oku.close();
        
        }catch(IOException e){
       
        }
        try{BufferedReader oku = new BufferedReader(new FileReader("C:\\Users\\tolga\\OneDrive\\Masaüstü\\VizeSinaviOncesiUygulama\\İSTANBUL.txt"));
                String satir = oku.readLine();
                while (satir != null) {
                    ist.add(satir);
                    satir = oku.readLine();
                }
        oku.close();
        
        }catch(IOException e){
       
        }
        try{BufferedReader oku = new BufferedReader(new FileReader("C:\\Users\\tolga\\OneDrive\\Masaüstü\\VizeSinaviOncesiUygulama\\ADANA.txt"));
                String satir = oku.readLine();
                while (satir != null) {
                    ada.add(satir);
                    satir = oku.readLine();
                }
        oku.close();
        
        }catch(IOException e){
       
        }
        try{BufferedReader oku = new BufferedReader(new FileReader("C:\\Users\\tolga\\OneDrive\\Masaüstü\\VizeSinaviOncesiUygulama\\ISPARTA.txt"));
                String satir = oku.readLine();
                while (satir != null) {
                    isp.add(satir);
                    satir = oku.readLine();
                }
        oku.close();
        
        }catch(IOException e){
       
        }
        for(int i=0;i<il.size();i++){
            jComboBox1.addItem(il.get(i));
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addItemListener(this::jComboBox1İtemStateChanged);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addItemListener(this::jComboBox2İtemStateChanged);

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1İtemStateChanged
        // TODO add your handling code here:
        String il=(String)jComboBox1.getSelectedItem();
        if(il==null) return;
        jComboBox2.removeAllItems();
        if(il.equals("İSTANBUL")){
            for(int k=0;k<ist.size();k++){
                jComboBox2.addItem(ist.get(k));
            }                  
        }
        if(il.equals("ADANA")){
            for(int k=0;k<ada.size();k++){
                jComboBox2.addItem(ada.get(k));
            }                  
        }
        if(il.equals("ISPARTA")){
            for(int k=0;k<isp.size();k++){
                jComboBox2.addItem(isp.get(k));
            }                  
        }

    }//GEN-LAST:event_jComboBox1İtemStateChanged

    private void jComboBox2İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2İtemStateChanged
        // TODO add your handling code here:
        String ilce=(String)jComboBox2.getSelectedItem();
        String il=(String)jComboBox1.getSelectedItem();
        jLabel1.setText(il+" -> "+ilce);
    }//GEN-LAST:event_jComboBox2İtemStateChanged
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SinavÖrnek5().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
